os: linux
dist: xenial
language: ruby
cache:
  - bundler
services:
  - postgresql
rvm:
  - 2.7.0

before_install:
  - gem install bundler
  - bundle config set --local deployment 'true'

script:
  - bundle install
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake spec